IF
  Range([PC],25)
  Global("cdgnsen1","%GnollStronghold%",0)
  GlobalLT("CDGnollQuest","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("cdgnsen1","%GnollStronghold%",1)
    CreateCreatureObject("%tutu_var%gnoll",Myself,10,0,0) 
END
    
IF
  Range([PC],15)
  Global("cdgnsen1","%GnollStronghold%",1)
  GlobalLT("CDGnollQuest","GLOBAL",2)
THEN
  RESPONSE #100
    SetGlobal("cdgnsen1","%GnollStronghold%",2)
    CreateCreatureObject("%tutu_var%gnoll",Myself,10,0,0) 
END
    